### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space  (happened twice in a row both after calculating the first set of results for the second enchantment seed)

### ISSUE THREAD

**Issue by M333r** [Earthcomputer/EnchantmentCracker#106]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3512055/enchcracker.log)

**Comment by Earthcomputer** [comment]
I acknowledge this is an issue. To reduce memory input though, always start both xp seeds with a 15 bookshelf input. I can see from the log you started the second one with 10.

**Comment by M333r** [comment]
Ah okay, I still got it to work because I just copied the first seed right as it was about to crash, but thanks

**Comment by Blaubeermuffin** [comment]
I got the OutOfMemoryError already with the first calculation with 15 bookshelves...
It worked fine yesterday, when I downloaded and used the enchcracker the first time, but today's another story.
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3513132/enchcracker.log)

**Comment by MCRcortex** [comment]
Have you tried closing open applications before running the cracker?

**Comment by Earthcomputer** [comment]
I don't know what to do about these out of memory issues, because if I increase the default amount of memory available to the cracker, people instead complain that they can't launch it in the first place.
You need to give it enough memory. The amount of memory it really needs is more than you might think (2+ gb). Edit the batch script to increase the amount of memory.

**Comment by Earthcomputer** [comment]
I think release 1.4.5 is as good as we're going to get with this memory problem for now.
