### ISSUE TITLE
Player seed not being calculated.

### ISSUE THREAD

**Issue by GlitchHead** [Earthcomputer/EnchantmentCracker#12]
Sometimes after doing the cracking process perfectly it still won't find the player seed. Take a look at the log file I saved.
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/1896971/enchcracker.log)

**Comment by Earthcomputer** [comment]
The two values at the bottom of the file, `22fc4eaf` and `550c33ff`, cannot be consecutive XP seeds. This means that there is either a bug in the XP seed cracker (unlikely since I haven't changed that part of the code since the initial release and it's worked for me and others every time), or you're doing something wrong.
If you are absolutely sure you are following all the instructions in the explanation video very precisely, including all the extra instructions in the video description, then I'll re-open this so we can investigate this further. In the mean time though, I'm going to close this issue.
