### ISSUE TITLE
[Feature Request] Can you add support for 1.16?

### ISSUE THREAD

**Issue by leoleoasd** [Earthcomputer/EnchantmentCracker#133]
1.16 added some new armors and tools.

**Comment by Earthcomputer** [comment]
Yes, I'm planning on it. I usually wait a few snapshots first, because sometimes they rebalance the enchantment statistics, and it would be a pain to keep up with their changing back and forth. If you can compile the code, you should be able to get a version in a few snapshots' time, otherwise, I will release a version on the day of the 1.16 release (or the day after if it's an inconvenient time for me).
