### ISSUE TITLE
Failed?

### ISSUE THREAD

**Issue by kknightyy** [Earthcomputer/EnchantmentCracker#135]
So when i calculate the seeds it just says "failed" all the time any fix?
![image](https://user-images.githubusercontent.com/32323367/75624314-3bb0ad80-5bee-11ea-89f6-fe347e778832.png)

**Comment by Earthcomputer** [comment]
?template failed

**Comment by Earthcomputer** [comment]
Ugh my bot is broken. This is what it was supposed to say:

This is usually caused by you doing one of a number of disallowed actions, such as sprinting, eating or being in beacon range. The Enchantment Cracker itself is not able to give any further information, so review the [list of disallowed actions](https://github.com/Earthcomputer/EnchantmentCracker/wiki/Tutorial#how-to-use-the-tool) and make sure you aren't doing any of them.

If you're really stuck, if you're on Minecraft 1.14 or newer you can install [clientcommands](https://github.com/Earthcomputer/clientcommands) which is a client-side mod and has a built-in Enchantment Cracker (so no need to use this one), and can give you more detailed information about where you're going wrong. You first have to enable `/ctemprule set enchantingPrediction true`, then use the built-in Enchantment Cracker in much the same way as you would use this one. Also run `/ctemprule set playerRNGMaintenance false` for more error catching. This mod requires the Fabric mod loader AND the Fabric API.
