### ISSUE TITLE
Calculate fail in 1.13.2 sever

### ISSUE THREAD

**Issue by BRONYAZAYCHIKH** [Earthcomputer/EnchantmentCracker#154]
The sever in 1.13.2 can't use it
Always shows fail in calculate
![image](https://user-images.githubusercontent.com/63533857/79062592-64889000-7cce-11ea-9720-4a661655340d.png)
help pls

**Comment by Earthcomputer** [comment]
?template failed

**Comment by BRONYAZAYCHIKH** [comment]
Thanks for the mod
but how to use the mod XD

**Comment by Earthcomputer** [comment]
Well first of all it explains how to use the mod in the bot message, and second of all it says the mod is for 1.14 or newer, so that part doesn't apply to you. I recommend the following:
- Checking the list of disallowed actions linked in the bot message.
- Trying out the mod in a newer version, to check you are doing the process correctly.
- Asking the server owner for a world download, if it works in the world download but not on the server, then some server plugin is messing it up.

**Comment by BRONYAZAYCHIKH** [comment]
Well , one of our member made a converter which allows me login the 1.13.2 sever in minecraft1.14.4 lol
That's why i want to know how to use 
Should i use cmd to use it xd 
i am really idiot in computer

**Comment by Earthcomputer** [comment]
Just follow the instructions, they are very detailed. I don't really have the time to hand-hold people for moving a file into a folder (which is what it takes to install a mod).
