### ISSUE TITLE
[Suggestion] Add a list of all the mods/plugins popular servers use that reset your XP seed/Player seed

### ISSUE THREAD

**Issue by zisis912** [Earthcomputer/EnchantmentCracker#170]
As I've seen in the comments of the video, many servers use plugins that (not on purpose) reset your XP seed/Player seed. Can you add a list of plugins/mods that reset your XP seed?

**edit:** by the way, is this diamond sword possible?
Unbreaking 3
sweeping 3
sharpness 4
looting 3
knockback 3
fire aspect 2

**Comment by Earthcomputer** [comment]
It's basically PaperMC, or any enchanting overhaul plugins.
I think that sword is possible, although the tool doesn't always find it because it stops simulating item throws after it reaches a certain threshold (it's very rare to get that sword in a single enchant). What's best is to enchant two swords and combine them.

**Comment by zisis912** [comment]
so paper makes this not work?

**Comment by Earthcomputer** [comment]
?template modded
