### ISSUE TITLE
Enchantment Cracker sometimes cannot find Player Seed

### ISSUE THREAD

**Issue by Vonr** [Earthcomputer/EnchantmentCracker#31]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/2227913/enchcracker.log)
May have something to do with me using Java 10?

**Comment by asquared31415** [comment]
This is probably because you accidentally changed the player RNG between enchants.  Make sure to never do any of the forbidden actions, including dropping any items, sprinting, eating, or taking damage.

Also make sure that you are not under any potion effects, including those from beacons.  If your particles are off, this will be hard to notice.
